USE [master]
GO

/****** Object:  Database [Pumox]    Script Date: 09.11.2022 18:52:45 ******/
CREATE DATABASE [Pumox]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'Pumox', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.MSSQLSERVER\MSSQL\DATA\Pumox.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'Pumox_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.MSSQLSERVER\MSSQL\DATA\Pumox_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
 WITH CATALOG_COLLATION = DATABASE_DEFAULT
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [Pumox].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [Pumox] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [Pumox] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [Pumox] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [Pumox] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [Pumox] SET ARITHABORT OFF 
GO

ALTER DATABASE [Pumox] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [Pumox] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [Pumox] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [Pumox] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [Pumox] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [Pumox] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [Pumox] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [Pumox] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [Pumox] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [Pumox] SET  ENABLE_BROKER 
GO

ALTER DATABASE [Pumox] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [Pumox] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [Pumox] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [Pumox] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [Pumox] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [Pumox] SET READ_COMMITTED_SNAPSHOT ON 
GO

ALTER DATABASE [Pumox] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [Pumox] SET RECOVERY FULL 
GO

ALTER DATABASE [Pumox] SET  MULTI_USER 
GO

ALTER DATABASE [Pumox] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [Pumox] SET DB_CHAINING OFF 
GO

ALTER DATABASE [Pumox] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [Pumox] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO

ALTER DATABASE [Pumox] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [Pumox] SET ACCELERATED_DATABASE_RECOVERY = OFF  
GO

ALTER DATABASE [Pumox] SET QUERY_STORE = OFF
GO

ALTER DATABASE [Pumox] SET  READ_WRITE 
GO


